name: Artifact Build

on: [pull_request] # Çekme istekleri (pull requests) açıldığında veya güncellendiğinde tetiklenir

jobs:
  build:
    runs-on: ubuntu-latest # İşin çalışacağı ortam
    steps:
    - uses: actions/checkout@v4 # Depo kodunu çekme
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew # gradlew betiğini çalıştırılabilir yapma
    - name: Run Gradle
      run: ./gradlew assemblePrereleaseDebug # Ön sürüm hata ayıklama APK'sını derleme
    - name: Upload Artifact
      uses: actions/upload-artifact@v4 # Derlenen APK'yı GitHub Artifact olarak yükleme
      with:
        name: pull-request-build
        # Ana proje klasörünüz 'cloudstream' (küçük harf) ise yolu güncelledik
        path: "cloudstream/app/build/outputs/apk/prerelease/debug/*.apk"
